### ISSUE TITLE
click-option-group only supports subset of click-supported python versions.

### ISSUE THREAD

**Issue by KSchopmeyer** [click-contrib/click-option-group#18]
Specifically click-option-group does not support python 2.7, 3.4, or 3.5 and that is obvious because setup.py states it and also includes pathlib which was not available in python 2.7 and pathlib.read_text() available only since python 3.5

Since our package (pywbemtools) supports all of the same python versions as click, we cannot use click-option-group since the complexity of having one set of menus for some python versions and another for other python versions is a significant piece of work.

It would be a big help if click-option-group supported the same versions of python as click so that all click users could integrate the groups since the groups is a real contribution to click.

We understand that python.org is no longer supporting python 2.7, but packages like ours cannot move as rapidly as the python core group (( :-) . We have users that have integrated our core package into OS releases and those take years to change. ( :-) so we have marked python 2.7 as deprecated to be removed in our next major release.

**Comment by espdev** [comment]
@KSchopmeyer @andy-maier

This issue is related to #17. This package does not have to support all versions of Python that Click supports. This is unofficial Click extension. Python 2.7 and 3.4 are dead, we will never support them again. I think Click in future versions will also drop support for outdated Python versions. Support of outdated Python versions does not allow you to use modern language features and decrease a technical debt in your software.

About 3.5. So be it. If you want you can create a PR with support 3.5. I will merge it after review. :)

**Comment by espdev** [comment]
@KSchopmeyer 

Just in case. There is another package for option groups: https://github.com/janLuke/cloup
The package supports Python >= 3.5, but it does not support groups constraints and option relations into groups.
