### ISSUE TITLE
Should Python 3.6 be supported?

### ISSUE THREAD

**Issue by JOJ0** [click-contrib/click-option-group#21]
Hi I just read an older issue that Python 3.5 is not supported. Should 3.6 work?

I am getting this on a Ubuntu Bionic machine:
```
Installed /usr/local/lib/python3.6/dist-packages/click_option_group-0.5.1-py3.6.egg
error: click 6.7 is installed but Click<8,>=7.0 is required by {'click-option-group'}
```

Thanks a lot!

**Comment by espdev** [comment]
Hi @JOJ0 
Python 3.6 is supported. The error says: `click 6.7 is installed but Click<8,>=7.0 is required`. 

I recommend using virtual environments (virtualenv) for your projects instead of system packages. They are usually outdated.

https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

**Comment by JOJ0** [comment]
Hi, thanks a lot for the answer,
yes I am aware of venv and I use it in my dev-environments. In this case it is about a sysadmin tool and in general it is IMHO better to use what the system provides and admins don't have to fiddle around with loading venvs.

So the question actually is. Will Click 7.0 run on a Stock-Python3.6 on Bionic. If you know by heart please tell me. Otherwise it is out of scope of this click-option-group question I guess.

Thanks!
